### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by TechnologyClassroom** [Alexey-T/CudaText_up#13]
I see in the README.md file the repo is MIT.  A LICENSE file would make this shown within the first page of the repo.

Steps to resolve:

1. In GitHub, start at the repository page.
1. Click on the `Add file` button and select `Create new file`.
1. In the `Name of your file...` text box, type in `LICENSE.md` and a new button will appear.
1. Click on the `Choose a license template` button.
1. Click on the MIT license.
1. Fill out the copyright line field with something like `Copyright 2018-2021 John Doe`.
1. Click on the `Review and Submit` button.
1. Beneath `Commit new file` enter a commit description.  I like to use the precise SPDX short identifier for the commit such as `MIT`.
1. Click on the `Commit directly to the x branch.` radio button.
9. Click on the `Commit new file` button.

**Comment by Alexey-T** [comment]
Thanks, done.
