### ISSUE TITLE
"unary operator expected" error

### ISSUE THREAD

**Issue by adnan360** [Alexey-T/CudaText_up#18]
When making changes for #17 I noticed an error. Running `./cudaup.sh -g -m` I got a (line number could be approximate):

```
./cudaup.sh: line 164: [: !=: unary operator expected
```

This probably happens because I haven't set `--ws` or `-w` param, so `$WS` is empty. So the line `if [ $WS != "" ]` raises this error. Adding double quotes to variable, like `if [ "$WS" != "" ]` will fix it. I've seen [people suggesting to add double quotes inside single brackets](https://stackoverflow.com/a/13618376) (`[ ... ]`) for this reason. This should be fixed throughout the script.

Edit: Add "throughout the script"

**Comment by Alexey-T** [comment]
Please make a PR ? Thanks

**Comment by giuliohome** [comment]
Having the same issue here, I'm going to consider the suggestion from @adnan360 now...

```
146,11) Hint: (4055) Conversion between ordinals and pointers is not portable
/home/giulio/pas/CudaText_up/src/ATSynEdit/atsynedit/atsynedit_cmd_bookmark.inc(174,13) Hint: (4055) Conversion between ordinals and pointers is not portable
atsynedit.pas(10244) Fatal: (10026) There were 1 errors compiling module, stopping
Fatal: (1018) Compilation aborted
Error: /usr/bin/ppcx64 returned an error exitcode
Error: (lazarus) Compile package atsynedit_package 2.10: stopped with exit code 1
Error: (lazarus) [TLazPackageGraph.CompileRequiredPackages] "Exit code 1"
./cudaup.sh: line 154: [: !=: unary operator expected
rm: cannot remove './src/CudaText/app/cudatext': No such file or directory
Error: (lazbuild) Broken dependency: atsynedit_cmp_package
cp: cannot stat './src/CudaText/app/cudatext': No such file or director
```

**Comment by Alexey-T** [comment]
forgot about this issue. fixing now.
