### ISSUE TITLE
Not running on Fedora 37

### ISSUE THREAD

**Issue by giuliohome** [Alexey-T/CudaText_up#19]
Not sure if it is related to[ my issue here](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/issues/488#issuecomment-1368419046) that I solved using stable instead of trunk though, but this is the error I'm gettting

```
atsynedit.pas(10244) Fatal: (10026) There were 1 errors compiling module, stopping
Fatal: (1018) Compilation aborted
Error: /usr/bin/ppcx64 returned an error exitcode
Error: (lazarus) Compile package atsynedit_package 2.10: stopped with exit code 1
Error: (lazarus) [TLazPackageGraph.CompileRequiredPackages] "Exit code 1"
rm: cannot remove './src/CudaText/app/cudatext': No such file or directory
Error: (lazbuild) Broken dependency: atsynedit_cmp_package
cp: cannot stat './src/CudaText/app/cudatext': No such file or directory
[giulio@fedora CudaText_up]$ 
```

**Comment by Alexey-T** [comment]
I dont see the actual compiling error in 'atsynedit' or in another place, in your log. can you show the entire log?

**Comment by giuliohome** [comment]
I have git cloned again and find here the full terminal output:

[mylog.txt](https://github.com/Alexey-T/CudaText_up/files/10328699/mylog.txt)

**Comment by Alexey-T** [comment]
reason:
`/home/giulio/pas/CudaText_up/src/ATSynEdit/atsynedit/atsynedit.pas(8652,9) Error: (5000) Identifier not found "IM_Context_Set_Cursor_Pos"`

how to fix. in Project Options dialog remove this 'define' GTK2_IME_CODE

![Screenshot from 2023-01-01 15-05-11](https://user-images.githubusercontent.com/4154978/210170041-f785dd2a-e38e-4598-9302-0fc5cf9dc1cb.png)

**Comment by Alexey-T** [comment]
wiki tells it!!!
`GTK2 error on ATSynEdit compiling regarding IME.`
https://wiki.freepascal.org/CudaText#How_to_compile_CudaText

**Comment by giuliohome** [comment]
Perfect! Applied also the other edit from the wiki for ATSynEdit  `atsynedit/atsynedit_package.lpk`.
Just to confirm that it is compiled and started fine now, but I see you already closed the issue.
Thank you for the immediate reply!
Happy new year!

**Comment by Alexey-T** [comment]
Happy new year!

**Comment by giuliohome** [comment]
fyi I'm still having a few issues 

```
[giulio@fedora ~]$ ./pas/CudaText_up/bin/linux-x86_64-/cudatext 
Gtk-Message: 14:18:05.069: Failed to load module "pk-gtk-module"
ERROR: Cannot find data: /home/giulio/.config/cudatext/data/toolbaricons/default_24x24
ERROR: Cannot find data: /home/giulio/.config/cudatext/data/sideicons/common_20x20
ERROR: Cannot find data: /home/giulio/.config/cudatext/py
[TGtk2WidgetSet.Destroy] WARNING: There are 5 unreleased DCs, a detailed dump follows:
[TGtk2WidgetSet.Destroy]  DCs:   00007F102E5ABE40 00007F102E5AB240 00007F102E5AAE40 00007F102E5AAA40 00007F102E5A9040
[TGtk2WidgetSet.Destroy] WARNING: There are 5 unreleased GDIObjects, a detailed dump follows:
[TGtk2WidgetSet.Destroy]   GDIOs: 00007F102C559640 00007F102C557FC0 00007F102C558B40 00007F102C5586C0 00007F102E1FEC40
[TGtk2WidgetSet.Destroy]   gdiFont: 5
```

In particular I'm not sure what to install on Fedora 37 for this: `Gtk-Message: 14:18:05.069: Failed to load module "pk-gtk-module"` or should I ignore this message about "pk-gtk-module"?
I assume there are a lot of fundamental plugins to install (?) because, aside from starting up, almost nothing is included in the compiled app, **I can't even open a folder** but only a file.
[Screencast from 2023-01-01 14-24-46.webm](https://user-images.githubusercontent.com/3272563/210172181-fb057879-5e50-42d9-956c-2fbee7e1cfe9.webm)


`ERROR: Exception in CudaText for cuda_project_man.new_project_open_dir: ModuleNotFoundError: No module named 'cuda_project_man'`

Is that error normal and expected? Sorry, am I missing something else from the wiki? I feel stupid, but I can't spot it atm...
As results from the screencast, the project manager is not showing.
Well, otherwise I'm reconsidering the install from flatpak :thinking:

**Comment by Alexey-T** [comment]
- 'ERROR: Cannot find data:' - to fix, just copy binary to the dir near 'data' dir and 'py' dir.
- GTK errors - same here. ignore.

**Comment by Alexey-T** [comment]
> I can't even open a folder but only a file.

Just copy binary near 'data' and 'py' dirs. ~~and configure the "pylib__linux" option.~~

**Comment by giuliohome** [comment]
So the pydir is ... I think...

```
/Contents/Resources/py
cuda_addonman         cuda_palette        cudatext_keys.py
cuda_comments         cuda_prefs          cudatext.py
cuda_emmet            cuda_project_man    cudatext_reset_plugins.py
cuda_insert_time      cuda_show_unsaved   cudax_css.py
cuda_lexer_detecter   cuda_snippet_panel  cudax_lib.py
cuda_make_plugin      cuda_sort           cudax_nodejs.py
cuda_multi_installer  cuda_tabs_list      sys
cuda_new_file         cudatext_cmd.py
cuda_options_editor   cudatext_init.py
```
and I do
```
[giulio@fedora cudatext.app]$ mv ../../../../bin/linux-x86_64-/cudatext .
[giulio@fedora cudatext.app]$ ls
Contents  cudatext
[giulio@fedora cudatext.app]$ ls Contents/
Info.plist  PkgInfo  Resources
```
and even better, I move it inside the Resources folder ...
```
[giulio@fedora Resources]$ ls
cudatext  cudatext.icns  data  py  settings_default
```
And now I can open a folder!

![image](https://user-images.githubusercontent.com/3272563/210173220-20e32227-2ce7-4455-80fa-d2c9d9ae296e.png)

Thank you!!!

**Comment by Alexey-T** [comment]
No, Resources folder is for macOS . You need usual dirs from my GitHub repo. From “app”

**Comment by giuliohome** [comment]
Ok :rofl:  but it was working great there... OK, moved like below

```
[giulio@fedora app]$ mv cudatext.app/Contents/Resources/cudatext .
[giulio@fedora app]$ ./cudatext
```

**Thank you again!!!**
