### ISSUE TITLE
replace "git pull origin master" with just "git pull"?

### ISSUE THREAD

**Issue by veksha** [Alexey-T/CudaText_up#20]
https://github.com/Alexey-T/CudaText_up/blob/5182c76ddf43c3168a5e8b93aaf35b59fb2b5d99/cudaup.sh#L121

the reason why i need it is because in my fork i renamed "origin" to "upstream".
`git pull` will do almost the same, but it will use whatever remote is specified for current branch.

**Comment by Alexey-T** [comment]
Agree. Pls make the PR

**Comment by Alexey-T** [comment]
Agree
