### ISSUE TITLE
switch bgrabitmap to custom branch

### ISSUE THREAD

**Issue by Alexey-T** [Alexey-T/CudaText_up#24]
@veksha I made last commit which changes current branch for 'bgrabitmap'. after cloning. i don't know how to fix code to keep that branch after __pulling__ too. i am weak in bash.

**Comment by veksha** [comment]
Hi. try this:

```diff
diff --git a/cudaup.sh b/cudaup.sh
index 8f5d71f..9fb2c44 100755
--- a/cudaup.sh
+++ b/cudaup.sh
@@ -138,6 +138,11 @@ then
 				stashed=true
 			fi
 			
+			# we need custom branch of 'bgrabitmap' for pulling too
+			if [[ "$temp" == "bgrabitmap" && "$(git symbolic-ref --short HEAD)" != "dev-bgrabitmap" ]]; then
+				git checkout dev-bgrabitmap
+			fi
+
 			originmaster=$(git rev-parse --abbrev-ref HEAD@{upstream}) # origin/master
 			origin_master=$(echo $originmaster | sed 's#/# #')         # origin master
 			

```

**Comment by veksha** [comment]
but i'm not sure. needs testing.

**Comment by Alexey-T** [comment]
on pull, you suggested '--depth 1' and '--no-tags'. they will break branches, right?. needs a fix?

**Comment by veksha** [comment]
1. i don't think it will break branches. why? BTW, that was not suggested by me, but by other user.

2. maybe add "git fetch" to my diff (to be sure that branch exists)?
```bash
if [[ "$temp" == "bgrabitmap" && "$(git symbolic-ref --short HEAD)" != "dev-bgrabitmap" ]]; then
  git fetch
  git checkout dev-bgrabitmap
fi
```

**Comment by Alexey-T** [comment]
@veksha @mix-7
i now reverted last change. because bgrabitmap was merged 'dev-.....' branch into 'master' branch.
