### ISSUE TITLE
Error when compiling on ARM64 for QT5

### ISSUE THREAD

**Issue by DUOLabs333** [Alexey-T/CudaText_up#25]
```
/home/system/Downloads/CudaText_up/src/CudaText/app/formmain.pas(3549,3) Error: (3026) Wrong number of parameters specified for call to "QTimer_singleShot"
/usr/lib/lazarus/lcl/units/aarch64-linux/qt5/qt5.ppu:qt56.pas(2535,11) Error: (5088) Found declaration: QTimer_singleShot(LongInt;QObjectH;PChar); CDecl;
/usr/lib/lazarus/lcl/units/aarch64-linux/qt5/qt5.ppu:qt56.pas(2536,11) Error: (5088) Found declaration: QTimer_singleShot(LongInt;QtTimerType;QObjectH;PChar); CDecl;
```

Maybe my lazarus version (2.2.1) is too old?

**Comment by Alexey-T** [comment]
Maybe Laz is old. Use 3.2. 

anyway, comment this line
```
  {$ifdef LCLQT5}
  //if you use Lazarus 2.x, this line cannot be compiled, so comment it
  QTimer_singleShot(10, @_QtDelayTimeOut);
  {$endif} 
```
it is check that runtime Qt5 lib is correct.
if it is not, on calling SaveAs dialog, app will crash.

**Comment by DUOLabs333** [comment]
Commenting out that line got me to linking. Unfortunately, I get the same error I got before: undefined reference to __libc_csu_init. This is likely due to fpc not finding crtbegin.o, even though it's already installed on my system.

**Comment by Alexey-T** [comment]
What FPC version? try to use the last release. If not ok, try the 'trunk' (last in git).
Use the fpcUpDeluxe and set there the 'trunk' option to use last git version.

**Comment by DUOLabs333** [comment]
Ok, so it turns out that on Arch Linux ARM, Lazarus is outdated by more than 2 years (though fpc is up to date).

**Comment by Alexey-T** [comment]
fpcUpDeluxe will ignore that sad fact, it can install any last version.

**Comment by DUOLabs333** [comment]
Hmmm, it turns out that compiling lazbuild fails with the same error.

**Comment by DUOLabs333** [comment]
It turns out the fix for fpc is in 3.2.4, which means I have to recompile that too. Is it possible for cudatext_up to point to a custom fpc directory, like with lazbuild?

**Comment by Alexey-T** [comment]
it don't support FPC path yet. try to fork it:

- lazarus dir is passed to lazbuild using `--lazdir` cmdline param
- FPC dir is passed to lazbuild using `--compiler=<ppcXXX>` param --> add it please

**Comment by DUOLabs333** [comment]
Interestingly, if I change the compiler parameter to my locally compiled version, I get `Can't find unit system used by emmet_package` for each of the packages used.

**Comment by Alexey-T** [comment]
it means that fpc.cfg file is not fully configured. 'cannot find unit system' error means it. I guess here. not sure!

**Comment by DUOLabs333** [comment]
I'll try again soon and see if I can get it working this time.

**Comment by DUOLabs333** [comment]
Is there a way to set fpcdeluxe to do a shallow clone (ie, `clone --depth 1`)?

**Comment by DUOLabs333** [comment]
Ok, I got it compiled using fpcupdeluxe!
