### ISSUE TITLE
DoGet broken

### ISSUE THREAD

**Issue by sikmir** [Alexey-T/CudaText_up#9]
```
$ ./cudaup.sh -g
...
./cudaup.sh: line 119: cd: https://github.com/bgrabitmap/bgrabitmap: No such file or directory
...
```
Caused by:
https://github.com/Alexey-T/CudaText_up/blob/fa29f13f0422d42a5f60ed98fe08b97ad51e239b/cudaup.repos#L1
https://github.com/Alexey-T/CudaText_up/blob/fa29f13f0422d42a5f60ed98fe08b97ad51e239b/cudaup.sh#L117

**Comment by Alexey-T** [comment]
@Artem3213212 , do you replace regex `https://github.com/Alexey-T/` with empty??? it fails on BGrabitmap URL. Lets fix the replace?
